spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/triple?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssafy
    password: ssafy

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: none

logging:
  level:
    org.hibernate.SQL: debug  # it will show all logs that hibernate made
    org.hibernate.type: trace
